language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

notifications:
    email: false

install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install codecov
  - pip install .

script:
  - py.test --cov=./

after_success:
  - codecov
